### PR TITLE
Fixing pspec_run to allow the use of non-future-array-shape uvdata

### PR DESCRIPTION
**Pull request by JianrongTan**
Currently the `pspec_run` command accepts `dsets` as a parameter, which is a list of UVData objects or string filepaths to UVData-compatible files. However, the acceptable UVData objects are implicitly using future_array_shape, which is not specified in the code. This PR aims to fix this issue.

### CODE REVIEW

**Review by adeliegorce — APPROVED** [review]
Thanks!

**Comment by JianrongTan** [comment]
Thanks @adeliegorce! I see `docs/readthedocs.org:hera-pspec — Read the Docs build failed!` in the checks. Is this a problem I should fix before merging and how should I do that?

**Comment by adeliegorce** [comment]
Ah, that's new... I'll have a look.

**Comment by adeliegorce** [comment]
OK @JianrongTan, this is a problem completely independent from your PR (as expected). So if your PR is very urgent, please go ahead and merge it. If not, keep an eye on [PR#388](https://github.com/HERA-Team/hera_pspec/pull/388) which solves the issue (awaiting approval) :)

**Comment by adeliegorce** [comment]
Hi @JianrongTan, the PR is all approved and ready to be merged!

**Pull request merged**
