### PR TITLE
pspec tapering functions draw from uvtools

### PR DESCRIPTION
**Pull request by nkern**
uvtools provides a much larger library of tapering functions than aipy, so our `PSpecData.taper` kwarg now draws from uvtools. One particular feature is the 7-term blackman harris window, which achieves more sidelobe suppression than the standard blackman harris window (aka 4-term blackman harris window). For users wanting to make power spectra of simulated FG + EoR datasets this may be necessary to achieve the required dynamic range. Addresses #221

### CODE REVIEW

**Comment by philbull** [comment]
There were a couple more instances of `aipy` tapering functions being used. I've now removed them, and now we no longer have `aipy` as a dependency!

**Comment by nkern** [comment]
@philbull awesome! feel free to approve and merge whenever you get a chance

**Comment by nkern** [comment]
@philbull so although we don't explicitly call `aipy` anymore, we are still reliant on packages that themselves have an `aipy` dependence, so maybe we should keep the `aipy` installation in our travis script?

**Comment by philbull** [comment]
Interestingly, the tests still seem to be passing... I'll re-run to see if anything breaks.

**Comment by nkern** [comment]
@philbull looks like this checks out. I'll merge it by the end of the day if you are okay with it, thanks!

**Pull request merged**
