### PR TITLE
Add ability to plot waterfalls of delay spectra

### PR DESCRIPTION
**Pull request by philbull**
Plot delay spectra ordered by time or baseline-pair. Solves #155.

### CODE REVIEW

**Comment by nkern** [comment]
Thanks for getting a start on this, its much-needed! One comment is, I'm not sure if its right to plot a waterfall of different baseline-pairs. It seems a little odd to do that, and perhaps is just confusing. Seems like when we say "waterfall", we should mean a single baseline-pair with a non-zero time axis which makes it a heatmap. If we want to make multiple blpair heatmaps, instead of concatenating them into a single plot, which I think is just a little confusing, we should be making multiple subplots... I can make this edit if you are ok w/ it and push to the branch

**Comment by philbull** [comment]
The idea was that this could eventually be used to make wedge plots too, which is why I allowed it to take multiple blpairs as an argument. It's not quite there yet though (e.g. it doesn't do the necessary averaging for you), so I agree more work is needed.

**Comment by acliu** [comment]
Is there an option to allow all the subplots to be on a common colour scale?

**Comment by nkern** [comment]
@acliu yes there is. you can specify the `vmin` and `vmax` parameters and all the colorscales are set to those limits

**Comment by nkern** [comment]
@philbull the other important change is that I enforced `matplotlib>=2.2` in the `setup.py` b/c I had `matplotlib=2.0` and it failed due to the `cbar.get_yticks` call (even though I see you had an explicit catch for it, it didn't work for me)... as well as `numpy>1.14` b/c that was causing some problems for me locally due to a `numpy==1.13` installation...

**Pull request merged**
